// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etwxzyuuckjlvykvumzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0d3h6eXV1Y2tqbHZ5a3Z1bXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTkzNTQsImV4cCI6MjA1ODgzNTM1NH0.eq7KbzZV4f8bDNrQzEfg7AbeOddp2wR51gRfIt7dQWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);